"""Source-cited research event definitions, selected without market-return filtering."""

EVENTS = [{'event_date': '2026-01-14',
  'market_date': '2026-01-14',
  'description': 'Some Al Udeid personnel advised to leave Qatar',
  'source_url': 'https://www.investing.com/news/commodities-news/some-personnel-were-advised-to-leave-us-military-base-in-qatar-diplomats-tell-reuters-4446427',
  'timing_basis': 'Reuters dated report before US close; exact initial event clock unavailable',
  'event_time_utc': '',
  'timing_uncertain': True},
 {'event_date': '2026-01-26',
  'market_date': '2026-01-26',
  'description': 'USS Abraham Lincoln and accompanying warships arrive in Middle East',
  'source_url': 'https://apnews.com/article/58e6da912f9167df94f913d7dafe5af4',
  'timing_basis': 'AP publication timestamp 17:19 UTC confirms availability before US close; not event '
                  'timestamp',
  'event_time_utc': '',
  'timing_uncertain': True},
 {'event_date': '2026-02-06',
  'market_date': '2026-02-06',
  'description': 'Iran and United States hold indirect talks in Oman',
  'source_url': 'https://apnews.com/article/32d621b98f7a3a68831f885d262bb70e',
  'timing_basis': 'Dated same-day report; exact initial event clock unavailable',
  'event_time_utc': '',
  'timing_uncertain': True},
 {'event_date': '2026-02-17',
  'market_date': '2026-02-17',
  'description': 'United States and Iran hold Geneva nuclear talks',
  'source_url': 'https://www.investing.com/news/commodities-news/us-and-iran-set-for-highstakes-nuclear-talks-in-geneva-as-threat-of-war-looms-4507859',
  'timing_basis': 'Dated daytime Geneva negotiations; exact result-release clock unavailable',
  'event_time_utc': '',
  'timing_uncertain': True},
 {'event_date': '2026-02-26',
  'market_date': '2026-02-26',
  'description': 'Geneva talks end with further negotiations announced',
  'source_url': 'https://wtop.com/world/2026/02/omans-foreign-minister-says-talks-between-iran-and-the-us-in-geneva-have-ended-but-will-resume-soon/',
  'timing_basis': 'AP syndicated bulletin timestamp 13:42 EST confirms availability before US close',
  'event_time_utc': '',
  'timing_uncertain': True},
 {'event_date': '2026-02-28',
  'market_date': '2026-03-02',
  'description': 'United States and Israel begin attacks on Iran',
  'source_url': 'https://apnews.com/article/04da58cbae991183f8b52ef5bf615963',
  'timing_basis': 'Saturday event assigned to next US trading session',
  'event_time_utc': '',
  'timing_uncertain': False},
 {'event_date': '2026-03-18',
  'market_date': '2026-03-18',
  'description': 'South Pars facilities attacked; Iran attacks Gulf energy facilities',
  'source_url': 'https://www.investing.com/news/world-news/iran-strikes-tel-aviv-with-cluster-warheads-in-retaliation-for-killing-of-security-chief-4567441',
  'timing_basis': 'Multiple events throughout dated session; overnight spillover possible',
  'event_time_utc': '',
  'timing_uncertain': True},
 {'event_date': '2026-04-07',
  'market_date': '2026-04-08',
  'description': 'United States and Iran announce two-week ceasefire',
  'source_url': 'https://www.upi.com/Top_News/US/2026/04/07/Iran-cease-fre/1461775613694/',
  'timing_basis': 'Announcement at 18:32 EDT after US close; next-session mapping',
  'event_time_utc': '2026-04-07T22:32:00Z',
  'timing_uncertain': False},
 {'event_date': '2026-04-12',
  'market_date': '2026-04-13',
  'description': 'Islamabad talks end without agreement',
  'source_url': 'https://apnews.com/article/04da58cbae991183f8b52ef5bf615963',
  'timing_basis': 'Sunday event assigned to next US trading session',
  'event_time_utc': '',
  'timing_uncertain': False},
 {'event_date': '2026-04-13',
  'market_date': '2026-04-13',
  'description': 'United States begins blockade of Iranian ports',
  'source_url': 'https://apnews.com/article/04da58cbae991183f8b52ef5bf615963',
  'timing_basis': 'Same-date event; co-occurs with first session after failed weekend talks',
  'event_time_utc': '',
  'timing_uncertain': True},
 {'event_date': '2026-04-17',
  'market_date': '2026-04-17',
  'description': 'Iran announces Strait of Hormuz reopening',
  'source_url': 'https://apnews.com/article/04da58cbae991183f8b52ef5bf615963',
  'timing_basis': 'Dated announcement; exact initial event clock unavailable',
  'event_time_utc': '',
  'timing_uncertain': True},
 {'event_date': '2026-04-21',
  'market_date': '2026-04-22',
  'description': 'Ceasefire extended while further talks remain pending',
  'source_url': 'https://www.cbsnews.com/live-updates/us-iran-war-trump-ceasefire-pakistan-peace-talks-ultimatum/',
  'timing_basis': 'CBS extension update at 16:22 EDT supports after-close mapping; update clock is not exact '
                  'announcement time',
  'event_time_utc': '',
  'timing_uncertain': True},
 {'event_date': '2026-05-03',
  'market_date': '2026-05-04',
  'description': 'CENTCOM announces May 4 start of Project Freedom shipping operation',
  'source_url': 'https://www.centcom.mil/MEDIA/PUBLIC-RELEASES/Article/4476318/us-military-supports-launch-of-project-freedom-in-strait-of-hormuz/',
  'timing_basis': 'Sunday official release; next US trading session',
  'event_time_utc': '',
  'timing_uncertain': False},
 {'event_date': '2026-06-07',
  'market_date': '2026-06-08',
  'description': 'Iran fires missiles at Israel following Beirut attack',
  'source_url': 'https://www.investing.com/news/world-news/us-eyes-iranian-assets-for-gulf-allies-reconstruction-source-says-4729626',
  'timing_basis': 'Sunday event assigned to next US trading session',
  'event_time_utc': '',
  'timing_uncertain': False},
 {'event_date': '2026-06-17',
  'market_date': '2026-06-17',
  'description': 'United States and Iran release signed interim agreement',
  'source_url': 'https://www.investing.com/news/world-news/g7-leaders-demand-ceasefire-in-lebanon-welcome-iran-deal-4746636',
  'timing_basis': 'Dated release and signing reports; exact initial event clock unavailable',
  'event_time_utc': '',
  'timing_uncertain': True},
 {'event_date': '2026-06-22',
  'market_date': '2026-06-22',
  'description': 'United States waives Iran sanctions following initial agreement talks',
  'source_url': 'https://www.investing.com/news/world-news/usiran-talks-go-into-day-2-after-trump-threats-hormuz-closure-4751698',
  'timing_basis': 'Dated policy action; exact initial publication clock unavailable',
  'event_time_utc': '',
  'timing_uncertain': True},
 {'event_date': '2026-06-25',
  'market_date': '2026-06-25',
  'description': 'Ship struck in Strait of Hormuz after June agreement',
  'source_url': 'https://www-cdn.abcnews.com/Politics/us-iran-ceasefire-mou-broke-timeline/story?id=134622392',
  'timing_basis': 'ABC retrospective dates initial shipping attack; intraday clock unavailable',
  'event_time_utc': '',
  'timing_uncertain': True},
 {'event_date': '2026-06-28',
  'market_date': '2026-06-29',
  'description': 'Iran and United States agree to halt exchanges and resume talks',
  'source_url': 'https://www.investing.com/news/world-news/us-carries-out-fresh-strikes-against-iran-after-tanker-struck-in-hormuz-escalating-hostilities-4764056',
  'timing_basis': 'Sunday agreement report assigned to next US trading session',
  'event_time_utc': '',
  'timing_uncertain': False},
 {'event_date': '2026-07-07',
  'market_date': '2026-07-07',
  'description': 'Shipping attacks followed by United States strikes and oil-license withdrawal',
  'source_url': 'https://www.investing.com/news/commodities-news/ship-hit-in-hormuz-as-millions-march-for-ayatollah-iran-says-no-talks-unless-trump-halts-threats-4778531',
  'timing_basis': 'Shipping incidents and subsequent action span session and after-close hours; next-session '
                  'robustness necessary',
  'event_time_utc': '',
  'timing_uncertain': True},
 {'event_date': '2026-07-27',
  'market_date': '2026-07-27',
  'description': 'United States pauses daily Iran strikes for negotiations',
  'source_url': 'https://apnews.com/article/670f077d2cf5de7614cfce4ad40e4aaa',
  'timing_basis': 'AP retrospective dates pause announcement; exact initial clock unavailable',
  'event_time_utc': '',
  'timing_uncertain': True},
 {'event_date': '2026-08-04',
  'market_date': '2026-08-04',
  'description': 'Qatar reports mediation progress; another vessel hit near Hormuz',
  'source_url': 'https://www.investing.com/news/commodities-news/status-of-usiran-talks-uncertain-as-ship-struck-in-hormuz-4832765',
  'timing_basis': 'Dated Qatar briefing and shipping report; exact event clocks unavailable',
  'event_time_utc': '',
  'timing_uncertain': True},
 {'event_date': '2026-08-17',
  'market_date': '2026-08-17',
  'description': 'Temporary ceasefire negotiating period expires without extension',
  'source_url': 'https://www.internazionale.it/ultime-notizie-reuters/2026/08/17/iran-threatens-to-go-on-offensive-in-strait-of-hormuz-if-diplomacy-with-us-fails',
  'timing_basis': 'Scheduled expiry plus same-day diplomatic reporting; partly anticipated event',
  'event_time_utc': '',
  'timing_uncertain': True},
 {'event_date': '2026-08-28',
  'market_date': '2026-08-28',
  'description': 'Mediators seek Hormuz reopening; Iran agrees to prepare conditions',
  'source_url': 'https://theprint.in/world/iran-war-mediators-focus-on-reopening-strait-of-hormuz/3027627/',
  'timing_basis': 'Reuters syndicated report at 16:30 IST before US close; underlying event clock unknown',
  'event_time_utc': '',
  'timing_uncertain': True},
 {'event_date': '2026-09-11',
  'market_date': '2026-09-11',
  'description': 'Saudi ministry announces East-West oil pipeline closure following attacks',
  'source_url': 'https://www.thenationalnews.com/news/2026/09/11/saudi-arabia-closes-east-west-oil-pipeline-following-attacks/',
  'timing_basis': 'Closure announced Friday; attacks occurred Thursday; original release clock unavailable',
  'event_time_utc': '',
  'timing_uncertain': True},
 {'event_date': '2026-09-13',
  'market_date': '2026-09-14',
  'description': 'Iranian cargo vessel struck and regional Hormuz talks postponed',
  'source_url': 'https://apnews.com/article/aa034da0d8226f5a3b4794b10afb8b3b',
  'timing_basis': 'Sunday events assigned to next US trading session',
  'event_time_utc': '',
  'timing_uncertain': False}]
